### ISSUE TITLE
'initial value' and 'new value' are fields blank

### ISSUE THREAD

**Issue by ghramsey** [Oliver2Goetz/AIPAKFileDifferentiation#1]
I am looking for differences between original commands pak and a modified version.
I broke  the door in tech support that needs the keycard.    I wanted it's orginal value so 
I can revert it to default but as shown in the screen shot. Both the 'initial value' and 'new value' 
fields are blank.

![image](https://user-images.githubusercontent.com/51859157/217646652-a8ef57ef-a1dd-42af-a008-666dfcb0a21d.png)
Also, IDK why there is a duplicated entry in that like.

Blank fields are not isolated to just this entry.  It seems lots of entries show both 
values blank even though there must be a difference if the program is showing them.

**Comment by Oliver2Goetz** [comment]
Hey ramsey, thanks for creating an issue!

Initial value and new value for parameters should behave like this:
CREATED: Should show an empty initial value and the current value for new value.
MODIFIED: Should show the initial and new value
DELETED: Should show the initial value and an empty new value.

So yes, there is an error here.
Why some differences appear twice is weird. As it seems it takes some(?) entities twice and thus also the parameters. Should hopefully be an easy fix since I can most likely check whether they already got any difference.

I will take a look at both of this once I have a bit more time than I currently have.

**Comment by ghramsey** [comment]
I think the dupicates may be be the proxy reference and the item inside it's own container.

**Comment by Oliver2Goetz** [comment]
Good thought! I have to explore deeper if that's really the case. Proxies however should be displayed as a PROXY and not as a FUNCTION as far as I know. I'll take a look at it

**Comment by Oliver2Goetz** [comment]
Summary - 2 errors are existent:
- sometimes initial and/or new value are empty (should behave according to how CREATED, MODIFIED and DELETED was originally intended)
- some entries are displayed twice -> figure out why (maybe PROXIES?)

**Comment by Oliver2Goetz** [comment]
Hey ramsey,

initial and new value not being shown is fixed in the newest version I just released.
Entity differences showing up twice will hopefully be fixed in an upcoming release version soon. I couldn't figure that part out yet.

Thanks for the report and sorry for the wait!

**Comment by Oliver2Goetz** [comment]
Hey ramsey,

showing modified entities just got fixed in the newest version (release v0.6).

Thank you so much for reporting this bug! This helps me out a ton.
