### ISSUE TITLE
Display parameter differences of new entities

### ISSUE THREAD

**Issue by ghramsey** [Oliver2Goetz/AIPAKFileDifferentiation#2]
![image](https://github.com/Oliver2Goetz/AIPAKFileDifferentiation/assets/51859157/1e995f08-1375-4983-9bfe-318150f59905)

My description is vague since I don't really know what this is categorized as.
PAK1 is vanilla Tech_Hub file; PAK 2 is my altered file.

This is a corpse I spawned in Mission 5.  The entity shows a short GUID that it's a function, but the intial and new values are blank.
It correctly shows blank on the 'initial field, but it should show there is a transform on the 'new' field.
Not sure if this is your program or the CathodeLib .API at fault.

I've seen this on other objects too, but I didn't get screenshots of those and can't reproduce other than this immediate issue.

**Comment by Oliver2Goetz** [comment]
Hey ramsey, thanks for creating an issue. I'm trying to figure out how to reproduce this problem.
To my understanding you created that entity yourself and want to see the parameters correct?

Here's a small clarification of how it currently works:
If an entity is created only the entity difference is shown. The parameter didn't exist before since the entity is new. That's why no parameter difference is shown.

Here's an example I built, the first entity is an already existing one and I added a transform parameter to it. The second entity I created myself and I also created the parameter there. As explained above, the second entity doesn't show a parameter difference since the entity is new:
![image](https://github.com/Oliver2Goetz/AIPAKFileDifferentiation/assets/44117499/caa232b4-3ec0-4979-85ce-c4aade0243f6)

Is that the case you have?
If yes, this might not be a bug and more of a feature I could add. Do you want a function like that?

**Comment by ghramsey** [comment]
OK.  That makes sense. This was a wholly new object so nothing was "changed" other than it doesn't exist in the stock file.
Indeed then this is not a bug. I was not 100% sure either if it was just how cathodelib works which seems to be the case.

It would sure be nice to see newly created entities that didn't or don't exist in the first file.  
If that is not too much difficulty to add as a feature it would be great.

**Comment by Oliver2Goetz** [comment]
Hey @ghramsey 
I implemented the described functionality (and also renamed the issue title).

Now if you create an entity the following will be displayed:
* like before: entity difference will be shown as CREATED
* new: all parameters of the new entity will be shown as a new parameter

**Comment by Oliver2Goetz** [comment]
@ghramsey I almost forgot to add. It's available in the newest version (v0.6.1)
I don't have an auto update so you have to download it manually yourself :c
